### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by papitosan** [Haruma-K/UnityUIPlayables#2]
Hi. this looks great but I can't install it in Unity.

If I use the URL nothings seems to happen in Unity.
So I trrid to download the zip and put the folder directly in the asset folder in Unity and it give console error that way.

Any ideas?

thanks

**Comment by Haruma-K** [comment]
Hi, thanks for the issue.

Did you try to install it using PakageManager?
If so, did you get any errors in the console?

**Comment by papitosan** [comment]
Yes, pasted this adress : https://github.com/Haruma-K/UnityUIPlayables.git?path=/Assets/UnityUIPlayables
with " add package from git url" in package manager, after clicking add button nothing happen.

**Comment by Haruma-K** [comment]
I tried it now with Unity 2020.2.7f1 and succeeded without any problems.

![examle](https://user-images.githubusercontent.com/47441314/120929407-e3872600-c723-11eb-843a-8b894249de33.gif)

I have no idea what's happening.

Can you install other third-party packages from GitHub?

**Comment by papitosan** [comment]
I have 2019.4.22.

 Usually I copy paste directly into the project,  not from url. It probably come from my setup.

**Comment by Haruma-K** [comment]
OK, if it seems to be a problem with this package, please contact me again.
