### ISSUE TITLE
Suggestion for the main readme 

### ISSUE THREAD

**Issue by cs-util** [Haruma-K/UnityUIPlayables#4]
Could you add to the main readme why this library is needed? So what can I do with it that I can't (or that is much harder) without it. I thought I already could animate arbitrary unity UI via animations but maybe I an missing something

**Comment by Haruma-K** [comment]
@cs-util 
Of course, you can also use Animation to animate the uGUI. If you want to animate uGUI using Timeline, you can do it easily and intuitively using this library.
Is that the answer?
